learning_templates/basic_app/urls.py
from django.urls import re_path
from basic_app import views

app_name = "basic_app"

urlpatterns = [
    re_path(r'^others/$', views.other, name="Other"),
    re_path(r'^relative/$', views.relative, name="Relative"),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from basic_app import views

urlpatterns = [
    re_path(r'^$', views.index, name="Index"),
    re_path(r'^basic_app/', include("basic_app.urls")),
    path('admin/', admin.site.urls),
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, "basic_app/index.html")

def other(request):
    return render(request, "basic_app/other.html")

def relative(request):
    return render(request, "basic_app/relative_url_templates.html")

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html>
<head>
	<title>Index Page</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
</head>
<body>

<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <div class="collapse navbar-collapse">
        <ul class="navbar-nav">
            <li class="nav-item"><a class="navbar-brand" href="{% url 'Index' %}">BRAND</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'basic_app:Other' %}">Other</a></li>
        </ul>
    </div>
    </div>
</nav>

<div class="container">
    {% block body_block %}
    {% endblock body_block %}
</div>


</body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% block body_block %}
<h1>Wellcome to Index</h1>
<h1>This is index.html page showing!</h1>
{% endblock body_block %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% block body_block %}
<h1>Wellcome to Other!</h1>
<h2>this is an example of template inheritance!</h2>
{% endblock body_block %}

learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html>
<head>
	<title>Relative Page</title>
</head>
<body>

<h1>Wellcome to Relative page</h1>
<a href="{% url 'basic_app:Other' %}">Link to Other page</a>
<br/>
<a href="{% url 'admin:index' %}">Link to admin page</a>
<br/>
<a href="{% url 'Index' %}">Link to Index page</a>

</body>
</html>